-- Orbit database schema for a new PostgreSQL or Supabase database.
-- Run this once after connecting to the target database.
-- This creates application tables only; it does not use Supabase Auth.

BEGIN;

-- Alembic uses this to recognize the database as being at the current schema revision.
CREATE TABLE IF NOT EXISTS public.alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

INSERT INTO public.alembic_version (version_num)
VALUES ('20260722_05')
ON CONFLICT (version_num) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.users (
    email TEXT PRIMARY KEY,
    username VARCHAR(30) UNIQUE,
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_username_format
        CHECK (username IS NULL OR username ~ '^[a-z0-9_]{3,30}$')
);

CREATE TABLE IF NOT EXISTS public.posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    published BOOLEAN NOT NULL DEFAULT TRUE,
    -- Public author label. New records contain the username.
    owner TEXT NOT NULL,
    -- Private immutable account identity used for authorization.
    author_email TEXT NOT NULL REFERENCES public.users(email) ON DELETE RESTRICT,
    likes_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_posts_likes_count_nonnegative CHECK (likes_count >= 0)
);

CREATE INDEX IF NOT EXISTS ix_posts_owner ON public.posts(owner);
CREATE INDEX IF NOT EXISTS ix_posts_author_email ON public.posts(author_email);

CREATE TABLE IF NOT EXISTS public.comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    -- Public author label. New records contain the username.
    owner TEXT NOT NULL,
    -- Private immutable account identity used for authorization.
    author_email TEXT NOT NULL REFERENCES public.users(email) ON DELETE RESTRICT,
    comment TEXT NOT NULL,
    likes_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_comments_likes_count_nonnegative CHECK (likes_count >= 0)
);

CREATE INDEX IF NOT EXISTS ix_comments_post_created_id
    ON public.comments(post_id, created_at, id);
CREATE INDEX IF NOT EXISTS ix_comments_owner ON public.comments(owner);
CREATE INDEX IF NOT EXISTS ix_comments_author_email ON public.comments(author_email);

CREATE TABLE IF NOT EXISTS public.post_likes (
    user_email TEXT NOT NULL REFERENCES public.users(email) ON DELETE RESTRICT,
    post_id INTEGER NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    CONSTRAINT pk_post_likes PRIMARY KEY (user_email, post_id)
);

CREATE INDEX IF NOT EXISTS ix_post_likes_post_id ON public.post_likes(post_id);

CREATE TABLE IF NOT EXISTS public.comment_likes (
    user_email TEXT NOT NULL REFERENCES public.users(email) ON DELETE RESTRICT,
    comment_id INTEGER NOT NULL REFERENCES public.comments(id) ON DELETE CASCADE,
    CONSTRAINT pk_comment_likes PRIMARY KEY (user_email, comment_id)
);

CREATE INDEX IF NOT EXISTS ix_comment_likes_comment_id ON public.comment_likes(comment_id);

-- Durable request replay records used by the API idempotency middleware.
CREATE TABLE IF NOT EXISTS public.idempotency_keys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope VARCHAR(512) NOT NULL,
    key VARCHAR(255) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    state VARCHAR(16) NOT NULL,
    response_status INTEGER,
    response_body TEXT,
    response_headers TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_idempotency_scope_key UNIQUE (scope, key)
);

-- Keep cached like counts synchronized with the durable like ledgers.
CREATE OR REPLACE FUNCTION public.sync_post_likes_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE public.posts SET likes_count = likes_count + 1 WHERE id = NEW.post_id;
    ELSE
        UPDATE public.posts SET likes_count = likes_count - 1 WHERE id = OLD.post_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_post_likes_count ON public.post_likes;
CREATE TRIGGER trg_sync_post_likes_count
AFTER INSERT OR DELETE ON public.post_likes
FOR EACH ROW EXECUTE FUNCTION public.sync_post_likes_count();

CREATE OR REPLACE FUNCTION public.sync_comment_likes_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE public.comments SET likes_count = likes_count + 1 WHERE id = NEW.comment_id;
    ELSE
        UPDATE public.comments SET likes_count = likes_count - 1 WHERE id = OLD.comment_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_comment_likes_count ON public.comment_likes;
CREATE TRIGGER trg_sync_comment_likes_count
AFTER INSERT OR DELETE ON public.comment_likes
FOR EACH ROW EXECUTE FUNCTION public.sync_comment_likes_count();

COMMIT;
